# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image:  python:3.9.10
clone:
  depth: full
pipelines:
  default:
#        - step:
#              name: Test
#              script:
#                - pip install -r requirements.txt
#                - python manage.py test
#      - step:
##            caches:
##             - pip
#            script:
##              - pip install -r requirements.txt
#              - python manage.py test

        - step:
              name: 'Build and Test'
              script:
                - echo "Your build and test goes here..."
        - step:
              name: 'Lint'
              script:
                - echo "Your linting goes here..."
        - step:
              name: 'Security scan'
              script:
                - echo "Your security scan goes here..."

        # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
        - step:
            name: 'Deployment to Staging'
            deployment: staging
            script:
              - echo "Your deployment to staging script goes here..."

        - step:
            name: 'Deployment to Production'
            deployment: production
            trigger: 'manual'
            caches:
                  - pip
            script:
            - pip install -r requirements.txt
            - git push origin main
            - pipe: atlassian/heroku-deploy:1.2.1
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_APP_NAME