# Generated by Django 4.0.1 on 2022-03-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0002_alter_buyerinfo_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerinfo',
            old_name='Cvv',
            new_name='cvv',
        ),
        migrations.RenameField(
            model_name='sellerinfo',
            old_name='ExpiryDate',
            new_name='expiry_date',
        ),
    ]
