# Generated by Django 4.0.3 on 2022-03-28 15:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0003_purchase_order_status_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerinfo',
            name='business_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
