# Generated by Django 4.0.3 on 2022-03-07 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('develop', '0004_alter_dishinfo_image_alter_sellerinfo_cardnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemSelected', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=5)),
                ('quantity', models.IntegerField()),
                ('total', models.CharField(max_length=10)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='develop.sellerinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
