"""
Django settings for ShareEats project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
import sys
from pathlib import Path
import django_heroku
from os.path import dirname, abspath
BASE_DIR = Path(__file__).resolve().parent.parent #dirname(dirname(abspath(__file__)))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from django.views import static

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9@4ztwax68^xop-u791t31)=hf%l&t0&lc_ggbdkm(m8z-t^3!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'develop',
    'crispy_forms',
    'phonenumber_field',
    'storages',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ShareEats.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ShareEats.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'shareeats',
#         'USER': 'postgres',
#         'PASSWORD': '123123',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

if 'test' in sys.argv:
    # config for testing
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'd34ha0e6ht7p1u',
            'USER': 'ddxtulbyilnnvs',
            'PASSWORD': '39bcd63cceebe99e93924eb0098206ed701f19e540af3abcc7ee082ff904f011',
            'HOST': 'ec2-52-71-161-140.compute-1.amazonaws.com',
            'PORT': '5432'
            ,
            'TEST': {
                'NAME': 'd34ha0e6ht7p1u',  # This is an important entry
            }
        }
    }
else:
    # Default configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'd7v8j1gf1115uk',
            'USER': 'cauikhfxvaggth',
            'PASSWORD': '3442684880261bc35b6f69efe8337896b0d9437b8f892f4349ef427e3b3b3be1',
            'HOST': 'ec2-34-230-110-100.compute-1.amazonaws.com',
            'PORT': '5432',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, '/develop/static')
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / 'develop/static/'

AWS_STORAGE_BUCKET_NAME = 'shareeats-storage-bucket'
AWS_S3_REGION_NAME = 'us-east-1'  # e.g. us-east-2
AWS_ACCESS_KEY_ID = 'AKIA5GS4IHOTZBGIYTDA'
AWS_SECRET_ACCESS_KEY = 'vpun0x8v1W38bgIZ76YqFIbjPoZamV9H+o3AHU0j'

# Tell django-storages the domain to use to refer to static files.
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
AWS_DEFAULT_ACL = None
STATICFILES_LOCATION ='staitc/'
STATICFILES_STORAGE = 'custom_storages.StaticStorage'
MEDIAFILES_LOCATION ='media/'
DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'
# stripe
STRIPE_PUBLIC_KEY = 'pk_test_51KLzyLC6KJdG6nXQ5xuYYYKndAYSYW9mSc9SFDTglJaxbJfizQ8xG1m3n2jT9VaiXKFOI8FpuseEFvdyLAphuFS600UjVEBK4b'
STRIPE_SECRET_KEY = 'sk_test_51KLzyLC6KJdG6nXQ5nPCdw37zF1BY7YzzQsDLsOjKTSVT0DtkXg3FSX3L9UGeQfMTbLxsIxjcBHoZs1N8ZN5N3tD00wVwOEHRE'
STRIPE_WEBHOOK_SECRET = ''

TWILIO_ACCOUNT_SID = 'ACf91579ced56697582b00416541947683'
TWILIO_AUTH_TOKEN = '9a2f8474b329324195b3ec3432f23eba'
TWILIO_PHONE_NUMBER = '+15134343957'
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGGING = {}
# user is directed to the dashboard when they successfully log in
LOGIN_REDIRECT_URL = '/loginverification'
CRISPY_TEMPLATE_PACK = 'bootstrap4'
AUTH_USER_MODEL = 'develop.User'
django_heroku.settings(locals())

#SMTP Configuration

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'shareeats88@gmail.com'
EMAIL_HOST_PASSWORD = 'jinja@348'
